version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

# Add additional package ecosystem clauses for your repository as per:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

  # Maintain dependencies for bundler
  # - package-ecosystem: "bundler"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for cargo
  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for composer
  # - package-ecosystem: "composer"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for docker
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for elm
  # - package-ecosystem: "elm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for gitsubmodule
  # - package-ecosystem: "gitsubmodule"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for gomod
  # - package-ecosystem: "gomod"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for gradle
  # - package-ecosystem: "gradle"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for maven
  # - package-ecosystem: "maven"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for mix
  # - package-ecosystem: "mix"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for npm
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for nuget
  # - package-ecosystem: "nuget"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for pip
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  # Maintain dependencies for terraform
  # - package-ecosystem: "terraform"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
