name: Dependabot auto-merge

on: 
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  dependabot:
    runs-on: self-hosted
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: ${{ secrets.github_token }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.github_token }}
