name: Lint Ansible

on:
  workflow_call:
    inputs:
      usePublicRunner:
        default: false
        required: false
        type: boolean

jobs:
  lint-ansible:
    runs-on: ${{ (inputs.usePublicRunner && 'ubuntu-latest') || 'self-hosted' }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3.2.0

      - name: Lint Ansible
        uses: ansible/ansible-lint-action@dd225474d15635904348151b9e694472ce0f62a8
        with:
          args: |
            -c .ansible-lint.yml
          # Temporary workaround for https://github.com/ansible/ansible-lint-action/issues/59
          override-deps: |
            rich>=9.5.1,<11.0.0
