name: Lint Markdown

on: 
  pull_request:
    branches:
      - master

jobs:
  lint-markdown:
    runs-on: self-hosted
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .