name: Lint Terraform

on:
  workflow_call:
    inputs:
      usePublicRunner:
        default: false
        required: false
        type: boolean

jobs:
  lint-terraform:
    runs-on: ${{ (inputs.usePublicRunner && 'ubuntu-latest') || 'self-hosted' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Terraform fmt
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: fmt -check -recursive -diff

      - name: Terraform init
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: init -backend=false

      - name: Terraform validate
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: validate
