name: Lint Dockerfile

on:
  workflow_call:
    inputs:
      usePublicRunner:
        default: false
        required: false
        type: boolean

jobs:
  lint-dockerfile:
    runs-on: ${{ (inputs.usePublicRunner && fromJSON('[ "ubuntu-latest" ]')) || 'self-hosted' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
