name: Lint Markdown

on:
  workflow_call:
    inputs:
      usePublicRunner:
        default: false
        required: false
        type: boolean

jobs:
  lint-markdown:
    runs-on: ${{ (inputs.usePublicRunner && 'ubuntu-latest') || 'self-hosted' }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3

      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
