name: Validate Codeowners

on:
  workflow_call:
    inputs:
      usePublicRunner:
        default: false
        required: false
        type: boolean
    secrets:
      GithubAccessToken:
        required: true

jobs:
  validate-codeowners:
    runs-on: ${{ (inputs.usePublicRunner && 'ubuntu-latest') || 'self-hosted' }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3.2.0

      - name: "Full check of CODEOWNERS"
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "duppatterns,owners,syntax"
          experimental_checks: "notowned"
          github_access_token: "${{ secrets.GithubAccessToken }}"
