name: Version and Create Release

on:
  workflow_call:
    inputs:
      usePublicRunner:
        default: false
        required: false
        type: boolean
    secrets:
      gh_token:
        required: true

jobs:
  release:
    runs-on: ${{ (inputs.usePublicRunner && 'ubuntu-latest') || 'self-hosted' }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3.3.0

      - name: Bump version and push tag
        id: versioner
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.gh_token }}

      - name: Create a GitHub release
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
          NOTES: ${{ steps.versioner.outputs.changelog }}
          TAG: ${{ steps.versioner.outputs.new_tag }}
          TITLE: Release ${{ steps.versioner.outputs.new_tag }}
        run: gh release create "$TAG" -t "$TITLE" -n "$NOTES"
