name: Version and Create Release

on:
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: versioner
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.github_token }}

      - name: Create a GitHub release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioner.outputs.new_tag }}
          release_name: Release ${{ steps.versioner.outputs.new_tag }}
          body: ${{ steps.versioner.outputs.changelog }}
